MindfulMusings/urls.py
from django.contrib import admin
from django.urls import path ,include

# for statics  urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import home_view , create_article_view ,article_detail, like_article , unlike_article , UpdateArticleView , DeleteArticleView ,ArticalListView


urlpatterns = [
    path('', home_view, name='home'), 
    path('new', create_article_view, name='new-article'),
    # path('article/<int:pk>/update/', update_article, name='update_article'),
    path('articles/', ArticalListView.as_view(), name='list-article'),
    path('article/<int:pk>/update/', UpdateArticleView.as_view(), name='update-article'),
    path('article/<int:id>/delete/', DeleteArticleView.as_view(), name='delete-article'),

    path('article/<int:id>/' ,article_detail, name='article-detail' ),
    path('article/<int:id>/like', like_article, name='like'),
    path('article/<int:id>/unlike', unlike_article, name='unlike')

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Categories(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(models.Model):
    hashtag = models.CharField(max_length=50)

    def __str__(self):
        return self.hashtag

    def save(self, *args, **kwargs):
        if not self.hashtag.startswith('#'):
            self.hashtag = '#' + self.hashtag
        super().save(*args, **kwargs)




class Article(models.Model):
    image = models.ImageField(null=True, default= "Featured_image.jpg")
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ManyToManyField(Categories)
    tag = models.ManyToManyField(Tag)
    likes = models.ManyToManyField(User, related_name='liked_articles', blank=True )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.author} on {self.post.title}"

blog/forms.py
from django import forms
from .models import Article, Comment 


class CreateArticalForm(forms.ModelForm):
    class Meta:
        model = Article
        # fields = ('title' , 'content', 'categories', 'tags')
        fields =('__all__')
        exclude = ['likes', 'author']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'rows': 2 }),  # Make the textarea smaller
        }

blog/views.py
from django.shortcuts import render,  redirect ,get_object_or_404  
from django.urls import reverse_lazy ,reverse
from django.http import JsonResponse
from django.db.models import Q
## using class base view for update article
from django.views.generic import UpdateView , DeleteView , ListView
from .models import Article, Comment ,Categories ,Tag
from .forms import CreateArticalForm , CommentForm 

# Create your views here.


def home_view(request):
    categories = Categories.objects.all()
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    articles = Article.objects.filter(
        Q(title__icontains=q)|
        Q(category__name__icontains=q)|
        Q(tag__hashtag__icontains=q)
    )
    



    ctx = {
        'articles':articles,
        'categories':categories
    }
    return render(request,'blog/home.html', ctx)

class ArticalListView(ListView):
    categories = Categories.objects.all()
    queryset = Article.objects.all()
    template_name = 'blog/articles_list.html'



def create_article_view(request):
    categories = Categories.objects.all()
    tags_list = Tag.objects.all()
    form = CreateArticalForm()
    
    if request.method == 'POST':

        category_name =request.POST.get('category')
        category, created  =Categories.objects.get_or_create(name = category_name)
        tag_hashtag = request.POST.get('tag')

        tag , created  = Tag.objects.get_or_create(hashtag = tag_hashtag)

        if not created:
            tag = Tag.objects.get(hashtag=tag_hashtag)
            category = Categories.objects.get(name = category_name)
            
        article = Article.objects.create(
            author = request.user,
            title = request.POST.get('title'),
            content = request.POST.get('content'),   
        )
        article.category.add(category)
        article.tag.add(tag)
        return redirect('home')
    else:
        form = CreateArticalForm()
    
    ctx = {
        'form': form,
        'categories': categories,
        'tags_list': tags_list,
        
    }
    return render(request, 'blog/create_article.html', ctx)

##### function base view

# def update_article(request, pk):
#     article = get_object_or_404(Article, pk=pk)

#     if request.method == 'POST':
#         form = CreateArticalForm(request.POST, instance=article)
#         if form.is_valid():
#             form.save()
#             return redirect('article_detail', id=pk)  # Redirect to the article detail page
#     else:
#         form = CreateArticalForm(instance=article)

#     return render(request, 'update_article.html', {'form': form, 'article': article})

## class base view

class UpdateArticleView(UpdateView):
    model = Article
    form_class = CreateArticalForm  # Use the form you've defined
    template_name = 'blog/update_article.html'
    # success_url = reverse_lazy('home')
    def get_success_url(self):
        # return reverse('articles:article-list')
        return reverse('list-article')

class DeleteArticleView(DeleteView):
    template_name =  'blog/delete_article.html'
    def get_object(self):
        id_ = self.kwargs.get("id")
        print(id_)
        return get_object_or_404(Article, id=id_)


    # success_url = reverse_lazy('home')

    def get_success_url(self):
        # return reverse('articles:article-list')
        return reverse('list-article')




def create_comment(request, article_id):
    article = get_object_or_404(Article, id=article_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = article
            comment.save()
            return redirect('article_detail', pk=article.id)  # Redirect to the article detail page
    else:
        form = CommentForm()

    return render(request, 'artical_detail.html', {'article': article, 'form': form})


def article_detail(request, id):
    categories = Categories.objects.all()
    article = get_object_or_404(Article, id=id)
    comments = Comment.objects.all()
    ## for artical create form
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = article
            comment.save()
            return redirect('article-detail', id=id)  # Redirect to the article detail page
    else:
        form = CommentForm()

    ctx = {
        'article':article,
        'comments':comments,
        'categories':categories,
        'form':form,
    }
    return render(request, 'blog/article_detail.html' , ctx)


    
def like_article(request, id):
    article = get_object_or_404(Article, id=id)
    
    if request.user not in article.likes.all():
        article.likes.add(request.user)
        article.save()
        
    return JsonResponse({'likes': article.likes.count()})

    # return redirect('article_detail', article_id=article.id)
    

def unlike_article(request, id):
    article = get_object_or_404(Article, id=id)
    
    if request.user in article.likes.all():
        article.likes.remove(request.user)
        article.save()
        
    return JsonResponse({'likes': article.likes.count()})

    # return redirect('article_detail', article_id=article.id)

blog/templates/blog/article_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="article-container">
  {% if request.user == article.author %}
  <div class="like-buttons">
    <button id="editButton" type="button">Edit</button>
    <button id="deleteButton" type="button">Delete</button>
  </div>
  {% endif %}
    <div class="article-detail-image">
      <img src="{{ article.image.url}}" alt="{{ article.title }}">
    </div>

  <h2 class="article-title">{{ article.title }}</h2>
  <p class="article-content">{{ article.content }}</p>
  <p>Likes: <span id="likes">{{ article.likes.count }}</span></p>
  
  <div class="like-buttons">
      <button id="unlikeButton" data-action="{% url 'unlike' article.id %}">Unlike</button>
      <button id="likeButton" data-action="{% url 'like' article.id %}">Like</button>
  </div>

  <div class="comments">
      {% for comment in comments %}
      <p>{{ comment.content }} - {{ comment.created_at|date }} @ {{ comment.author }}</p>
      {% endfor %}
  </div>

  <div class="comment-form">
    <form action="" method="post" class="comment-form">
        {% csrf_token %}
        <div class="form-group">
            <!-- {{ form.content.label_tag }} -->
            <label for="">Write your comment</label>
            <div class="comment-input-container">
                {{ form.content }}
            </div>
        </div>
        <button type="submit" class="comment-button">Comment</button>
    </form>
</div>
<script>

  // detail page js 
document.getElementById("editButton").addEventListener('click', function(){
  var updateUrl = "{% url 'update-article' article.id %}";
  window.location.href = updateUrl;
})

document.getElementById("deleteButton").addEventListener("click", function() {
  var deleteUrl = "{% url 'delete-article' article.id %}";
  window.location.href = deleteUrl;
});




const likeButton = document.getElementById('likeButton');
  const unlikeButton = document.getElementById('unlikeButton');
  const likesSpan = document.getElementById('likes');

  likeButton.addEventListener('click', () => {
    updateLikes(likeButton.getAttribute('data-action'));
  });

  unlikeButton.addEventListener('click', () => {
    updateLikes(unlikeButton.getAttribute('data-action'));
  });

  console.log('hi')

  function updateLikes(url) {
    fetch(url, {
      method: 'GET',  // Or 'GET' depending on your view
      headers: {
        'X-Requested-With': 'XMLHttpRequest',
        'X-CSRFToken': getCookie('csrftoken')
      }
    })
    .then(response => response.json())
    .then(data => {
      likesSpan.textContent = data.likes;
    })
    .catch(error => {
      console.error('Error updating likes:', error);
    });
  }

  function getCookie(name) {
    const value = `; ${document.cookie}`;
    const parts = value.split(`; ${name}=`);
    if (parts.length === 2) return parts.pop().split(';').shift();
  }
</script>

{% endblock %}

blog/templates/blog/articles_list.html
{% extends 'base.html' %}
{% block content %}


{% for instance in object_list %}
    {% comment %} <p>{{instance.id}} - <a href='{{ instance.get_absolute_url}}'>{{instance.title}}</a></p> {% endcomment %}
    <p>{{instance.id}} - <a href='{% url 'article-detail' instance.id%}'>{{instance.title}}</a></p>
    
    {% endfor %} 



{% endblock content %}

blog/templates/blog/create_article.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST" class="form-container">{% csrf_token %}
    <div class="form_row" style= "margin-bottom:10px;">
        {{ form.image.label_tag }}
        {{ form.image }}
    </div>
    <div class="form_row" >
        {{ form.title.label_tag }}
        {{ form.title }}
    </div>
    <div class="form_row">
        {{ form.content.label_tag }}
        {{ form.content }}
    </div>

    <div class="form_row">
        <div class="form__group">
            <label for="category">Choose/Enter category</label>
            <input type="text" name="category" list="category-list" style= "width:95%;">
            <datalist id="category-list">
                {% for category in categories_list %}
                    <option value="{{ category.name }}">{{ category.name }}</option>
                {% endfor %}
            </datalist>
        </div>
    </div>

    <div class="form_row">
        <div class="form__group">
            <label for="tag">Choose/Enter tag</label>
            <input type="text" name="tag" list="tag-list" style= "width:95%;">
            <datalist id="tag-list">
                {% for tag in tags_list %}
                    <option value="{{ tag.hashtag }}">{{ tag.hashtag }}</option>
                {% endfor %}
            </datalist>
        </div>
    </div>

    <button type="submit">Create</button>
</form>
{% endblock content %}

blog/templates/blog/create_article_old.html
{% extends 'base.html' %}

{% block content %}
    <h1> Create Article </h1>



    <form method="POST" action="">
        {% csrf_token %}
        
        <label for="id_title">Title:</label>
        <input type="text" id="id_title" name="title" value="{{ article.title }}" required>
        <br>
        
        <label for="id_content">Content:</label>
        <textarea id="id_content" name="content" required>{{ article.content }}</textarea>
        <br>
        


        <label for="id_categories">Categories:</label>

        <input required type="text" name="categories" list="categories-list">
<datalist id="categories-list">
    {% for category in categories %}
        <option value="{{ category.name }}">{{ category.name }}</option>
    {% endfor %}
</datalist>




              {% comment %} <label for="id_categories">Categories:</label>
              <input required type="text" name="categories" id="categories" list="categories-list">
              <button type="button" id="add-category-button">Add New Category</button>
              
              <datalist id="categories-list">
                  {% for category in categories %}
                  <option value="{{ category.name }}">
                  {% endfor %}
              </datalist>
              
              <div id="new-category-input" style="display: none;">
                  <input type="text" id="new-category" placeholder="Enter new category">
                  <button type="button" id="save-new-category">Save</button>
              </div>
               {% endcomment %}
              
              

        <label for="id_tag">Tags:</label>
        <input required type="text" name="tag" list="Tag-list">
              <datalist id="tag-list">
                <select id="tag_hashtag">
                    {% for t in tag %}
                  <option value="{{ t.hashtag }}">{{ t.hashtag }}</option>
                  {% endfor %}
                </select>
              </datalist>
        
        <button type="submit">Create</button>



        <script>
          const addCategoryButton = document.getElementById("add-category-button");
          const newCategoryInput = document.getElementById("new-category-input");
          const newCategoryField = document.getElementById("new-category");
          const saveNewCategoryButton = document.getElementById("save-new-category");
      
          addCategoryButton.addEventListener("click", () => {
              addCategoryButton.style.display = "none";
              newCategoryInput.style.display = "block";
              newCategoryField.focus();
          });
      
          saveNewCategoryButton.addEventListener("click", () => {
              const newCategoryValue = newCategoryField.value;
              if (newCategoryValue.trim() !== "") {
                  const dataList = document.getElementById("categories-list");
                  const option = document.createElement("option");
                  option.value = newCategoryValue;
                  dataList.appendChild(option);
                  newCategoryField.value = "";
              }
              newCategoryInput.style.display = "none";
              addCategoryButton.style.display = "block";
          });
      </script>
      

{% endblock content %}

blog/templates/blog/delete_article.html
{% extends 'base.html' %}
{% block content %}

<form action="." method="POST" class="form-container">{% csrf_token %}
    <h1>DO you want to delete the post "{{ object.title }}"?</h1>
    {% comment %} <p><input type="submit" value="Yes" /> <a href="../">Cancil</a> </p> {% endcomment %}
    <button type="submit">Yes</button> <button id="cancelButton" type="button">No</button>


</form>


{% endblock content %} 

blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
   <div class="like-buttons">
        
        <button id="listbutton" type="button">Articles List</button>
    </div>
    <div class="container">
        {% for article in articles %}
            <div class="article">
                <div class="article-image">
                    <img src="{{ article.image.url }}" alt="{{ article.title }}">
                </div>
                <div class="article-content">
                    <h2>{{ article.title }}</h2>
                    <p>{{ article.content|truncatechars:150 }}</p>
                    <a href="{% url 'article-detail' article.id %}">Read more</a>
                
                </div>
            </div>
        {% endfor %}

    <script>
        document.getElementById("listbutton").addEventListener('click', function(){
  var Url = "{% url 'list-article' %}";
  window.location.href = Url;
})
    </script>

{% endblock content %}

blog/templates/blog/update_article.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update your article</h1>
    <form action="" method="POSt"  class="form-container"> {% csrf_token %}   
        {{form.as_p}}
        <button type="submit">Update</button> <button id="cancelButton" type="button">Cancel</button>
        <!-- <p><a href="../">Cancil</a> </p> -->
        
    </form>




    <!-- <script>
        document.getElementById("cancelButton").addEventListener('click', function(){
            window.location = "../"
        })
       
    </script> -->
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WanderlustWritings</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <header>
        <nav>
            <h1>MindfulMusings</h1>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'new-article' %}">Create Article</a></li>
                <li class="dropdown">
                    <a href="#">Categories</a>
                    <div class="dropdown-content">
                        {% for category in categories %}
                        {% if category %}
                        <a href="{% url 'home' %}?q={{category.name}} ">{{category.name}}
                            <span>({{category.article_set.all.count}})</span> </a>
                        {% endif %}
                        {% endfor %}
                    </div>
                </li>
            </ul>

            <div class="search-form">
                <form action="#" method="get">
                    <input type="text" name="q" placeholder="Search articles">
                    
                        <button type="submit">Search</button>
                    
                </form>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        replace me
        {% endblock content %}
    </main>

    <footer>

    </footer>
    <script src="{% static 'script/script.js' %}"></script>
</body>

</html>